theme: minima
title: Portfolio
author: Bruna Moura Correia
email: mcorreia.bruna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 “Simplicity is the soul of efficiency.” – Austin Freeman

# social links
github_username:  brunacorreia # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
